dist: xenial
language: python
python:
  - 3.7
install:
  - pip install -r requirements.txt
  - python setup.py -q install
script:
  - python setup.py test && cram specs/
branches:
  only:
    - master

