dist: xenial
language: python
python:
  - 3.7
install:
  - pip install flake8
before_install:
  - python -m pip install --upgrade pip wheel
script:
  # - python setup.py test && cram specs/
  - flake8 . --exit-zero
branches:
  only:
    - master
    - patch-1

