language: python
python:
  - 2.6
  - 2.7
  - 3.3
install:
  - pip install cram unidecode mako Jinja2 markdown docutils Attest-latest
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]];
      then pip install --use-mirrors argparse ordereddict;
    fi
  - python setup.py -q install
script:
  - python setup.py test && cram specs/
branches:
  only:
    - master
    - /^feature\/.*$/
    - /^legacy\/.*$/
notifications:
  irc:
    channels:
      - "irc.freenode.org#acrylamid"
    on_success: change
    on_failure: change
    template: "%{repository} (%{commit}) : %{message}, %{build_url}"
